services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Acseo\SyliusYoastSEOPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    Acseo\SyliusYoastSEOPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    Acseo\SyliusYoastSEOPlugin\Menu\AdminProductFormMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.product.form, method: addItems }

    Acseo\SyliusYoastSEOPlugin\Controller\CustomProductController:
        autowire: true
        autoconfigure: true
        public: true