name: CI Pipeline

on:
    push:
        branches: [ master ]
        tags: [ '*' ]
    pull_request:

env:
    PHP_VERSION: 8.2

jobs:

    build-macos:
        name: Build macOS
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Castor cache
                uses: actions/cache@v4
                id: cache-castor-macos
                with:
                    path: /Users/runner/.cache/castor
                    key: castor-macos:php-${{ env.PHP_VERSION }}-${{ github.sha }}
                    restore-keys: castor-macos:php-${{ env.PHP_VERSION }}-
            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   uses: actions/cache@v4
                id: cache-composer
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: composer2-php-macos:${{ env.PHP_VERSION }}-${{ github.sha }}
                    restore-keys: composer2-php-macos:${{ env.PHP_VERSION }}-
            -   uses: ./.github/actions/build
                with:
                    repack_os: darwin
                    compile_os: macos
                    php: ${{ env.PHP_VERSION }}

    build-linux:
        name: Build Linux
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Castor cache
                uses: actions/cache@v4
                id: cache-castor-linux
                with:
                    path: /home/runner/.cache/castor
                    key: castor-linux:php-${{ env.PHP_VERSION }}-${{ github.sha }}
                    restore-keys: castor-linux:php-${{ env.PHP_VERSION }}-
            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   uses: actions/cache@v4
                id: cache-composer
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: composer2-php-linux:${{ env.PHP_VERSION }}-${{ github.sha }}
                    restore-keys: composer2-php-linux:${{ env.PHP_VERSION }}-
            -   uses: ./.github/actions/build
                with:
                    repack_os: linux
                    compile_os: linux
                    php: ${{ env.PHP_VERSION }}

    create-plugin:
        name: Create plugin and install it
        runs-on: ubuntu-latest
        needs: [ build-linux ]
        if: "!startsWith(github.ref, 'refs/tags/')"
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: gd, intl, json
                    ini-values: date.timezone=UTC
                    tools: symfony-cli
            -   name: Download binary
                uses: actions/download-artifact@v4
                with:
                    name: plugin-maker.linux
                    path: ./bin
            -   run: chmod +x bin/plugin-maker.linux
                shell: bash
            -   name: Create a plugin
                run: ./bin/plugin-maker.linux create --no-interaction "Sylius Bazinga Plugin"
                shell: bash
            -   name: Install the plugin
                working-directory: ./SyliusBazingaPlugin
                run: make install

    release-artifacts:
        name: Release artifacts
        runs-on: ubuntu-latest
        needs: [ build-macos, build-linux ]
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    path: ./artifacts
            -   run: tree ./artifacts
                shell: bash
            -   name: Upload files to the release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        ./artifacts/plugin-maker.linux/plugin-maker.linux
                        ./artifacts/plugin-maker.linux.phar/plugin-maker.linux.phar
                        ./artifacts/plugin-maker.darwin/plugin-maker.darwin
                        ./artifacts/plugin-maker.darwin.phar/plugin-maker.darwin.phar
